import numpy as np 
import matplotlib.pyplot as plt
import time
import warnings

warnings.filterwarnings("ignore")

hat = ['gary', 'stu', 'samwise']

choose = np.random.randint(len(hat), size=1000000)

print('I am the All Powerful Chooser of Book Club Books!!!!\n')
time.sleep(2)
print('Let\'s see who is in the hat this week:')
time.sleep(2)
for i in range(0, len(hat)-1):
    print(hat[i] + ', ')
    time.sleep(2)
print('and ' + hat[len(hat)-1] + '.\n ')
time.sleep(2)
print('To prove I am unbiased I have picked the names randomly 1000000 times, observed my unbiasedness\n')
time.sleep(2)
x, y = np.histogram(choose, bins=len(hat))
fig, ax = plt.subplots()
ax.bar(y[:-1], x, 0.5)
ax.set_ylabel('frequency')
ax.set_xticks(np.arange(0, len(hat)-1, (len(hat)-1)/len(hat)))
ax.set_xticklabels(hat)
plt.tight_layout()
plt.show(block=False)
print('Damn! I am so unbiased when I pick randomly that many times!\n')
plt.pause(5)
plt.close()
time.sleep(2)
print('Now to choose who is going to pick the next book!\n')
time.sleep(2)
print('Who will it be??\n')
time.sleep(1)
print('Being random!')
time.sleep(1)
print('Being random!')
time.sleep(1)
print('Being random!')
time.sleep(1)
print('Being random!')
time.sleep(1)
print('Being random!')
time.sleep(1)
print('Being random!')
time.sleep(1)
print('Being random!')
time.sleep(1)
print('Being random!')
time.sleep(1)
print('Being random!')
time.sleep(1)
print('Being random!')
time.sleep(1)
choose = np.random.randint(len(hat), size = 1000000)
x, y = np.histogram(choose, bins=len(hat))
a = np.argmax(x)
print('The book is to be choosen by:')
time.sleep(1)
for i in range(0, 50):
    print(hat[a])
print('Hope you were able to read that this time')
